server:
  port: 1001
  tomcat:
    max-threads: 100
spring:
  application:
    name: uaa-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_db?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: 47.98.107.200
    password: 123456
    port: 6379
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: org.hibernate.dialect.MySQLSInnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.107.200:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 9999

  main:
    allow-bean-definition-overriding: true